### ISSUE TITLE
Default Sidebar Tab

### ISSUE THREAD

**Issue by jdjdjdjdjdjd** [jdjdjdjdjdjd/TW5-Material#1]
from google groups:
https://groups.google.com/forum/#!msg/tiddlywiki/Fk5FivkKNvg/a7lHSgLiBAAJ

Default Sidebar Tab doesn't work.

**Comment by Adam-Antios** [comment]
When I want to change the default tab in the sidebar I go to

Control Panel - Settings - Default Sidebar Tab

choose the one I want use, then save and reload.  After I reload the tab I chose is not open at default.

To my TiddlyWiki it seems that

Control Panel - Settings - Default Sidebar Tab

doesn't do anything.

**Comment by jdjdjdjdjdjd** [comment]
Wait a minute... I never noticed this before, but this looks like a bug in TW itself, or a function that is not really clear. 

Head over to https://tiddlywiki.com/ the sidebar open there is TableOfContents but at the settings tiddler the default is set to the "Open" tab

Maybe "Default sidebar tab" only means when the state tiddler does not exist, and not for refreshing the page. 

I will ask around at the groups.

**Comment by jdjdjdjdjdjd** [comment]
I re-asked this over at the groups, in the meantime, you can create this tiddler so that the sidebar tab is refreshed during browser refresh / startup:

title: **your-preferred-title**

tag: **$:/tags/StartupAction**

text: 
```
<$list filter="[prefix[$:/state/tab/sidebar]]" variable="sidebarTab">
<$action-deletetiddler $tiddler=<<sidebarTab>>/>
</$list>
```

**Comment by Adam-Antios** [comment]
Yeah what you say about the [tiddlywiki.com](https://tiddlywiki.com) is true but I don't think this is a bug, more like a feature because if you download an empty TiddlyWiki and try it, it works fine.
