### ISSUE TITLE
documentation FAB buttons

### ISSUE THREAD

**Issue by hchaase** [jdjdjdjdjdjd/TW5-Material#11]
I cant seem to figure out where the secondarry fab buttons are?? could you write something so people like me can understand where to look for them

**Comment by hchaase** [comment]
I finally found out how they work on pc. I have to press and hold the fab button and drag up. This would be nice info to have in some sort of comment

**Comment by jdjdjdjdjdjd** [comment]
thanks @hchaase, will add this note on the next release
