### ISSUE TITLE
tiddlers don't fit the space of the search list

### ISSUE THREAD

**Issue by jdjdjdjdjdjd** [jdjdjdjdjdjd/TW5-Material#2]
from google groups:
https://groups.google.com/forum/#!msg/tiddlywiki/Fk5FivkKNvg/a7lHSgLiBAAJ

If you press the search button and write, for instance, "Sidebar" in the shadow tiddlers, then there is a bug because the available tiddlers don't fit the space of the list.

**Comment by jdjdjdjdjdjd** [comment]
I can't replicate this issue (or maybe I misunderstand?)

**Comment by Adam-Antios** [comment]
Press search and in the search bar write Sidebar. From the search tabs pick Shadows and you will see that the list of tiddlers appearing don't fit the list

![selection_001](https://user-images.githubusercontent.com/17729838/42177258-c562a428-7e34-11e8-9902-f843e76f6709.png)

**Comment by jdjdjdjdjdjd** [comment]
Oh, wow! This isn't an issue for me using Windows10 Chrome V67
Please let me know your OS and the browser you're using, I think this might be a compatibility issue but I'm not yet sure.

**Comment by jdjdjdjdjdjd** [comment]
Oh, wow! This isn't an issue for me using Windows10 Chrome V67
Please let me know your OS and the browser you're using, I think this might be a compatibility issue but I'm not yet sure.

**Comment by jdjdjdjdjdjd** [comment]
Sorry about accidentally closing this! damn it JD, look before you click!

**Comment by Adam-Antios** [comment]
You are right! I just checked on Chromium and it works fine!

I use KDE Neon and this problem is on Firefox 60.0.2 (64-bit)

**Comment by jdjdjdjdjdjd** [comment]
Ooh.. I haven't used Firefox in a while. Please wait while I try ways to fix this (days, probably, i'm really sorry for the busy schedule)

**Comment by Adam-Antios** [comment]
Don't worry at all! You don't have any obligation to even fix it. I just mention here the bugs so you know about them. I will be glad if they are fixed but I don't expect it or take it for granted. 

This is your theme and you built it in your free time for you, remember that you don't have any obligations to fix the bugs for anyone else. You can even stop maintaining it altogether if you feel like it. 

Please don't disrupt your everyday schedule. Thank you for your work though.

**Comment by hchaase** [comment]
had you have the time to look at this?? I realy like your theme but this is not so nice.. the problem is also, that I cant scroll down to see searchresults further down!

**Comment by jdjdjdjdjdjd** [comment]
I managed to replicate the bug my side after upgrading my TW, and an unrelated issue popped up related to story river scrolling.

I fixed both by using a <$scrollable> widget with parameter fallthrough="no", and adding an overflow attribute to the searchlist dropdown.

The updates will be released today, I don't know how to github so I'll just be using google groups to communicate the release
