### ISSUE TITLE
Code Block Appearance

### ISSUE THREAD

**Issue by Adam-Antios** [jdjdjdjdjdjd/TW5-Material#3]
I don't know if this is the intended behaviour but the code blocks in the Material Theme show like that

![selection_001](https://user-images.githubusercontent.com/17729838/42548935-47fd539e-84d2-11e8-9330-82983b01cc26.png)

when in a native TiddlyWiki they show like that

![selection_002](https://user-images.githubusercontent.com/17729838/42548987-942e3666-84d2-11e8-868b-fd87d58952a4.png)

As you see, code blocks in the Material Theme are rendered like there are a lot of lines of code concatenated together and if you pay attention you can notice the border between lines

![selection_001](https://user-images.githubusercontent.com/17729838/42549095-19a69f36-84d3-11e8-86c4-34289f2cca61.png)

**Comment by silvyn** [comment]
I don't reproduce it. Maybe JD have updated the code.

**Comment by Adam-Antios** [comment]
That is good to know. Maybe it is a browser specific issue.

**Comment by silvyn** [comment]
FYI, on Fedora 28 with Firefox 61.0.2

**Comment by jdjdjdjdjdjd** [comment]
this also isn't an issue on my Chrome84. I'll mark this as closed now
