### ISSUE TITLE
"More actions" List Bug

### ISSUE THREAD

**Issue by Adam-Antios** [jdjdjdjdjdjd/TW5-Material#4]
When you open the list with the button "More actions" then as you can see there is a bug. The list gets overlapped by the the toolbar of the tiddlers.

![selection_001](https://user-images.githubusercontent.com/17729838/42878135-a400055c-8a94-11e8-8651-7ee7f082e316.png)

![selection_002](https://user-images.githubusercontent.com/17729838/42878136-a42562c0-8a94-11e8-95c8-f63568ff49f6.png)

**Comment by silvyn** [comment]
I think it's Sticky titles option of TW.

(but seems to be useful to have the first tittle tiddler not cover by top bar navigation).

**Comment by Adam-Antios** [comment]
Hey, even if that is due to an option it shouldn't hinder the menu like that.

**Comment by silvyn** [comment]
Yep, but it's an experimental (or it was), and don't set by default for this reason. It doesn't work on all browser.
Just see there is no more this alert on setting in English, maybe french translation to update but : 

"Lorsqu'on fait défiler le déroulé, les titres des tiddlers s'accrochent en haut de la fenêtre du navigateur tant que le contenu de leur tiddler est visible. **Attention** : ne fonctionne pas du tout avec Chrome, et peut causer quelques problèmes de mise en page dans Firefox".

**Comment by Adam-Antios** [comment]
I understand, that is why I post it as an issue here so to draw attention to it and let the dev know that is works like that on Firefox.

**Comment by jdjdjdjdjdjd** [comment]
A related change I'll incorporate into the next release of this theme, is by default disabling the theme's styling of tiddler frames. This is due to me warming up to the default tiddler frame style, and for fewer buggy experiences with tiddler frames.
