### ISSUE TITLE
Material theme breaks layout for other themes

### ISSUE THREAD

**Issue by nblumoe** [jdjdjdjdjdjd/TW5-Material#9]
After installing the material theme, the layout for other themes is broken. An additional sidebar is added in the footer region (see the screenshot below). This additional sidebar is hidden when the material theme is active.

This seems to be related to the gesture plugin because it gives and error about "swipe missing" when I uninstall material theme as well as the hammerjs plugin.

![material_ _le_goog_s_material_theme](https://user-images.githubusercontent.com/995628/52177646-4539cd00-27c4-11e9-8c7d-57ce6143b3ac.png)

**Comment by hchaase** [comment]
I get a different error, whenever I change to another theme the sidebar and buttons completely disappear and make the wiki useless!!! this is disturbing 

whats going on jD?

![billede](https://user-images.githubusercontent.com/2864323/64690594-12119780-d491-11e9-8a9f-d5804cfb57c5.png)

**Comment by jdjdjdjdjdjd** [comment]
That is a major bug! Yikes! I've fixed it in the upcoming release by not-revealing / unlisting the Template and Stylesheet of this theme when text of `$:/themes` is not `$:/themes/jd/Material` (TW list widget is my favorite, such a versatile one)
